import React, { useEffect, useMemo, useState } from 'react';
import RoomsManager from './RoomsManager.jsx';

const STORAGE_KEY = 'time-maker-v3';
const LEGACY_KEY = 'time-maker-phase-1-v1';
const uid = () => (globalThis.crypto?.randomUUID ? globalThis.crypto.randomUUID() : `${Date.now()}-${Math.random()}`);
const DAYS = [['mon','Monday'],['tue','Tuesday'],['wed','Wednesday'],['thu','Thursday'],['fri','Friday'],['sat','Saturday'],['sun','Sunday']];
const ROOM_TYPES = ['No specialist room','General classroom','Science lab','Computer room','Art room','Music room','Drama space','Sports facility','Workshop / DT room','Kitchen / food room'];
const GROUP_TYPES = ['Form','Teaching group','Set','Option group','Sixth form','Mixed year','Intervention'];
const defaultBlocks = [
  ['Period 1','lesson','08:55','09:50'],['Period 2','lesson','09:55','10:50'],['Break','break','10:50','11:10'],
  ['Period 3','lesson','11:10','12:05'],['Period 4','lesson','12:10','13:05'],['Lunch','break','13:05','14:05'],
  ['Period 5','lesson','14:05','15:00'],['Period 6','lesson','15:05','16:00'],
].map(([name,type,start,end]) => ({ id: uid(), name, type, start, end }));
const defaultAvailability = () => Object.fromEntries(DAYS.map(([key]) => [key, !['sat','sun'].includes(key)]));

const initialState = {
  school:{name:'',academicYear:'2026/27',timezone:'Europe/London',cycle:'one-week'},
  days:DAYS.map(([key,label])=>({key,label,enabled:!['sat','sun'].includes(key)})), blocks:defaultBlocks, dayOverrides:{},
  keyStages:[{id:uid(),name:'KS3',years:['Year 7','Year 8','Year 9']},{id:uid(),name:'KS4',years:['Year 10','Year 11']},{id:uid(),name:'KS5',years:['Year 12','Year 13']}],
  terms:[{id:uid(),name:'Autumn',start:'2026-09-01',end:'2026-12-18',halfStart:'2026-10-26',halfEnd:'2026-10-30'},{id:uid(),name:'Spring',start:'2027-01-04',end:'2027-03-26',halfStart:'2027-02-15',halfEnd:'2027-02-19'},{id:uid(),name:'Summer',start:'2027-04-12',end:'2027-07-23',halfStart:'2027-05-31',halfEnd:'2027-06-04'}],
  departments:['Science','Mathematics','English','Humanities','Languages','PE','Arts','Technology','SEND','Sixth Form'], staff:[], classes:[], curriculumRequirements:[], rooms:[],
};
function hydrate(saved={}){return {...initialState,...saved,school:{...initialState.school,...(saved.school||{})},days:saved.days||initialState.days,blocks:saved.blocks||initialState.blocks,dayOverrides:saved.dayOverrides||{},keyStages:saved.keyStages||initialState.keyStages,terms:saved.terms||initialState.terms,departments:saved.departments||initialState.departments,staff:saved.staff||[],classes:saved.classes||[],curriculumRequirements:saved.curriculumRequirements||[],rooms:saved.rooms||[]};}
function load(){try{const now=localStorage.getItem(STORAGE_KEY);if(now)return hydrate(JSON.parse(now));const legacy=localStorage.getItem(LEGACY_KEY);if(legacy)return hydrate(JSON.parse(legacy));}catch{}return initialState;}
function Section({eyebrow,title,description,children,actions}){return <section className="panel"><div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div>{actions&&<div className="section-actions">{actions}</div>}</div>{children}</section>}
function Metric({label,value,note,className=''}){return <div className="metric-card"><span>{label}</span><strong className={className}>{value}</strong><small>{note}</small></div>}
function Empty({title,text,action,onClick}){return <div className="empty-state"><div className="empty-icon">+</div><strong>{title}</strong><p>{text}</p><button className="primary" onClick={onClick}>{action}</button></div>}

function SchoolSetup({data,setData}){
  const enabled=data.days.filter(d=>d.enabled); const [day,setDay]=useState(enabled[0]?.key||'mon');
  const blocks=data.dayOverrides?.[day]||data.blocks;
  const updateBlock=(i,f,v)=>setData(p=>{if(p.dayOverrides?.[day]){const arr=[...p.dayOverrides[day]];arr[i]={...arr[i],[f]:v};return {...p,dayOverrides:{...p.dayOverrides,[day]:arr}}}const arr=[...p.blocks];arr[i]={...arr[i],[f]:v};return {...p,blocks:arr}});
  const toggleOverride=(on)=>setData(p=>{const o={...(p.dayOverrides||{})};if(on)o[day]=p.blocks.map(b=>({...b,id:uid()}));else delete o[day];return {...p,dayOverrides:o}});
  return <><div className="page-title"><div><span className="eyebrow">PHASE 1</span><h1>School setup</h1><p>Set the school week, day structure, year groups and academic calendar.</p></div></div>
  <div className="summary-grid compact"><Metric label="Teaching days" value={enabled.length} note="enabled days"/><Metric label="Lesson blocks" value={data.blocks.filter(b=>b.type==='lesson').length} note="standard day"/><Metric label="Year groups" value={data.keyStages.reduce((n,k)=>n+k.years.length,0)} note="configured"/><Metric label="Cycle" value={data.school.cycle==='two-week'?'A / B':'1 week'} note="pattern"/></div>
  <Section eyebrow="1A · PROFILE" title="School profile"><div className="form-grid three"><label><span>School name</span><input value={data.school.name} onChange={e=>setData(p=>({...p,school:{...p.school,name:e.target.value}}))}/></label><label><span>Academic year</span><input value={data.school.academicYear} onChange={e=>setData(p=>({...p,school:{...p.school,academicYear:e.target.value}}))}/></label><label><span>Cycle</span><select value={data.school.cycle} onChange={e=>setData(p=>({...p,school:{...p.school,cycle:e.target.value}}))}><option value="one-week">One week</option><option value="two-week">Week A / B</option></select></label></div></Section>
  <Section eyebrow="1B · WEEK" title="Teaching week"><div className="day-toggles">{data.days.map(d=><label key={d.key} className={`day-toggle ${d.enabled?'enabled':''}`}><input type="checkbox" checked={d.enabled} onChange={e=>setData(p=>({...p,days:p.days.map(x=>x.key===d.key?{...x,enabled:e.target.checked}:x)}))}/><span>{d.label}</span><small>{d.enabled?'Teaching day':'Off'}</small></label>)}</div></Section>
  <Section eyebrow="1C · PERIODS" title="School day" description="Use custom times for exceptional days if needed."><div className="subtoolbar"><div className="day-selector">{enabled.map(d=><button key={d.key} className={day===d.key?'selected':''} onClick={()=>setDay(d.key)}>{d.label.slice(0,3)}</button>)}</div><label className="switch-label"><input type="checkbox" checked={Boolean(data.dayOverrides?.[day])} onChange={e=>toggleOverride(e.target.checked)}/> Custom times</label></div><div className="block-list">{blocks.map((b,i)=><div className={`time-block ${b.type}`} key={b.id}><input className="block-name" value={b.name} onChange={e=>updateBlock(i,'name',e.target.value)}/><select value={b.type} onChange={e=>updateBlock(i,'type',e.target.value)}><option value="lesson">Lesson</option><option value="break">Break</option><option value="activity">Activity</option></select><input type="time" value={b.start} onChange={e=>updateBlock(i,'start',e.target.value)}/><span className="to">to</span><input type="time" value={b.end} onChange={e=>updateBlock(i,'end',e.target.value)}/><button className="danger-icon" onClick={()=>setData(p=>p.dayOverrides?.[day]?{...p,dayOverrides:{...p.dayOverrides,[day]:p.dayOverrides[day].filter((_,x)=>x!==i)}}:{...p,blocks:p.blocks.filter((_,x)=>x!==i)})}>×</button></div>)}</div><button className="secondary" onClick={()=>setData(p=>({...p,blocks:[...p.blocks,{id:uid(),name:'New period',type:'lesson',start:'16:05',end:'17:00'}]}))}>+ Add block</button></Section>
  <Section eyebrow="1D · YEARS" title="Key stages and year groups"><div className="ks-grid">{data.keyStages.map((ks,ki)=><div className="ks-card" key={ks.id}><div className="ks-title"><input value={ks.name} onChange={e=>setData(p=>({...p,keyStages:p.keyStages.map((x,i)=>i===ki?{...x,name:e.target.value}:x)}))}/></div><div className="year-tags">{ks.years.map((y,yi)=><div className="year-row" key={yi}><input value={y} onChange={e=>setData(p=>({...p,keyStages:p.keyStages.map((x,i)=>i===ki?{...x,years:x.years.map((a,j)=>j===yi?e.target.value:a)}:x)}))}/></div>)}</div><button className="text-button" onClick={()=>setData(p=>({...p,keyStages:p.keyStages.map((x,i)=>i===ki?{...x,years:[...x.years,'New year']}:x)}))}>+ Add year</button></div>)}</div></Section>
  <Section eyebrow="1E · TERMS" title="Term dates"><div className="term-list">{data.terms.map((t,i)=><div className="term-card" key={t.id}><input className="term-title" value={t.name} onChange={e=>setData(p=>({...p,terms:p.terms.map((x,j)=>j===i?{...x,name:e.target.value}:x)}))}/>{['start','end','halfStart','halfEnd'].map(f=><label key={f}><span>{({start:'Starts',end:'Ends',halfStart:'Half term starts',halfEnd:'Half term ends'})[f]}</span><input type="date" value={t[f]||''} onChange={e=>setData(p=>({...p,terms:p.terms.map((x,j)=>j===i?{...x,[f]:e.target.value}:x)}))}/></label>)}</div>)}</div></Section></>
}

function StaffManager({data,setData}){
  const enabled=data.days.filter(d=>d.enabled); const [search,setSearch]=useState(''); const [filter,setFilter]=useState('All');
  const add=()=>setData(p=>({...p,staff:[...p.staff,{id:uid(),name:'',initials:'',department:p.departments[0]||'',subjects:[],fte:1,contractHours:37.5,maxPeriods:42,ppaPeriods:5,leadershipPeriods:0,maxDaily:6,maxConsecutive:4,formTutor:'',availability:defaultAvailability(),notes:''}]}));
  const update=(id,f,v)=>setData(p=>({...p,staff:p.staff.map(s=>s.id===id?{...s,[f]:v}:s)}));
  const visible=data.staff.filter(s=>(filter==='All'||s.department===filter)&&`${s.name} ${s.initials} ${(s.subjects||[]).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
  return <><div className="page-title"><div><span className="eyebrow">PHASE 2</span><h1>Staff manager</h1><p>Define teaching capacity, subjects and availability.</p></div><button className="primary" onClick={add}>+ Add staff member</button></div><div className="summary-grid compact"><Metric label="Staff" value={data.staff.length} note="entered"/><Metric label="FTE" value={data.staff.reduce((n,s)=>n+Number(s.fte||0),0).toFixed(1)} note="combined"/><Metric label="Teaching ceiling" value={data.staff.reduce((n,s)=>n+Number(s.maxPeriods||0),0)} note="periods/week"/><Metric label="Part-time" value={data.staff.filter(s=>Number(s.fte)<1).length} note="below 1.0 FTE"/></div>
  <Section eyebrow="2A · STAFF" title="Teaching staff"><div className="table-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search staff…"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{data.departments.map(d=><option key={d}>{d}</option>)}</select></div>{!data.staff.length?<Empty title="No staff yet" text="Add teachers and their timetable limits." action="Add first teacher" onClick={add}/>:<div className="staff-list">{visible.map(s=><article className="staff-card" key={s.id}><div className="staff-card-head"><div className="avatar">{s.initials||'?'}</div><div className="staff-identity"><input className="name-input" value={s.name} onChange={e=>update(s.id,'name',e.target.value)} placeholder="Full name"/><div className="mini-grid"><label><span>Initials</span><input value={s.initials} onChange={e=>update(s.id,'initials',e.target.value.toUpperCase())}/></label><label><span>Department</span><select value={s.department} onChange={e=>update(s.id,'department',e.target.value)}>{data.departments.map(d=><option key={d}>{d}</option>)}</select></label></div></div><button className="danger-outline small" onClick={()=>setData(p=>({...p,staff:p.staff.filter(x=>x.id!==s.id)}))}>Remove</button></div><div className="staff-fields"><label className="wide"><span>Subjects</span><input value={(s.subjects||[]).join(', ')} onChange={e=>update(s.id,'subjects',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label><label><span>FTE</span><input type="number" step="0.1" min="0.1" max="1" value={s.fte} onChange={e=>update(s.id,'fte',e.target.value)}/></label><label><span>Max periods</span><input type="number" value={s.maxPeriods} onChange={e=>update(s.id,'maxPeriods',e.target.value)}/></label><label><span>PPA</span><input type="number" value={s.ppaPeriods} onChange={e=>update(s.id,'ppaPeriods',e.target.value)}/></label><label><span>Leadership</span><input type="number" value={s.leadershipPeriods} onChange={e=>update(s.id,'leadershipPeriods',e.target.value)}/></label><label><span>Max/day</span><input type="number" value={s.maxDaily} onChange={e=>update(s.id,'maxDaily',e.target.value)}/></label><label><span>Max consecutive</span><input type="number" value={s.maxConsecutive} onChange={e=>update(s.id,'maxConsecutive',e.target.value)}/></label></div><div className="availability"><div><strong>Working days</strong><small>Untick unavailable days.</small></div><div className="availability-days">{enabled.map(d=><label className={s.availability?.[d.key]!==false?'available':''} key={d.key}><input type="checkbox" checked={s.availability?.[d.key]!==false} onChange={e=>update(s.id,'availability',{...s.availability,[d.key]:e.target.checked})}/>{d.label.slice(0,3)}</label>)}</div></div></article>)}</div>}</Section></>
}

function ClassesManager({data,setData}){
  const years=data.keyStages.flatMap(k=>k.years); const [search,setSearch]=useState('');
  const add=(type='Teaching group')=>setData(p=>({...p,classes:[...p.classes,{id:uid(),name:'',year:years[0]||'',type,subject:'',size:20,lessonsPerWeek:1,optionBlock:'',teacherId:'',notes:''}]}));
  const update=(id,f,v)=>setData(p=>({...p,classes:p.classes.map(c=>c.id===id?{...c,[f]:v}:c)}));
  const visible=data.classes.filter(c=>`${c.name} ${c.year} ${c.subject}`.toLowerCase().includes(search.toLowerCase()));
  return <><div className="page-title"><div><span className="eyebrow">PHASE 3</span><h1>Classes & groups</h1><p>Create forms, sets, options and teaching groups.</p></div><button className="primary" onClick={()=>add()}>+ Add group</button></div><div className="summary-grid compact"><Metric label="Groups" value={data.classes.length} note="entered"/><Metric label="Student places" value={data.classes.reduce((n,c)=>n+Number(c.size||0),0)} note="across groups"/><Metric label="Lesson demand" value={data.classes.reduce((n,c)=>n+Number(c.lessonsPerWeek||0),0)} note="periods/week"/><Metric label="Option groups" value={data.classes.filter(c=>c.type==='Option group').length} note="option blocks"/></div>
  <Section eyebrow="3A · GROUPS" title="Class and group builder"><div className="quick-create">{GROUP_TYPES.map(t=><button className="secondary small" key={t} onClick={()=>add(t)}>+ {t}</button>)}</div><div className="table-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search groups…"/><div/></div>{!data.classes.length?<Empty title="No groups yet" text="Add forms, classes or option groups." action="Add first group" onClick={()=>add()}/>:<div className="class-table-wrap"><table className="data-table"><thead><tr><th>Group</th><th>Type</th><th>Year</th><th>Subject</th><th>Size</th><th>Lessons/wk</th><th>Option block</th><th>Teacher</th><th/></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><input value={c.name} onChange={e=>update(c.id,'name',e.target.value)}/></td><td><select value={c.type} onChange={e=>update(c.id,'type',e.target.value)}>{GROUP_TYPES.map(t=><option key={t}>{t}</option>)}</select></td><td><select value={c.year} onChange={e=>update(c.id,'year',e.target.value)}><option value="">Mixed</option>{years.map(y=><option key={y}>{y}</option>)}</select></td><td><input value={c.subject} onChange={e=>update(c.id,'subject',e.target.value)}/></td><td><input type="number" min="0" value={c.size} onChange={e=>update(c.id,'size',e.target.value)}/></td><td><input type="number" min="0" value={c.lessonsPerWeek} onChange={e=>update(c.id,'lessonsPerWeek',e.target.value)}/></td><td><input value={c.optionBlock||''} onChange={e=>update(c.id,'optionBlock',e.target.value)}/></td><td><select value={c.teacherId||''} onChange={e=>update(c.id,'teacherId',e.target.value)}><option value="">Any suitable</option>{data.staff.map(s=><option key={s.id} value={s.id}>{s.initials||s.name}</option>)}</select></td><td><button className="danger-icon" onClick={()=>setData(p=>({...p,classes:p.classes.filter(x=>x.id!==c.id),curriculumRequirements:p.curriculumRequirements.filter(r=>r.targetGroupId!==c.id)}))}>×</button></td></tr>)}</tbody></table></div>}</Section></>
}

function CurriculumManager({data,setData}){
  const years=data.keyStages.flatMap(k=>k.years); const [search,setSearch]=useState('');
  const add=(seed={})=>setData(p=>({...p,curriculumRequirements:[...p.curriculumRequirements,{id:uid(),name:seed.name||'',year:seed.year||years[0]||'',subject:seed.subject||'',targetType:seed.targetType||'year',targetGroupId:seed.targetGroupId||'',lessonsPerWeek:seed.lessonsPerWeek??1,doublePeriods:0,maxSameDay:1,spread:'balanced',roomType:'No specialist room',staffingMode:seed.teacherId?'fixed':'any-qualified',teacherId:seed.teacherId||'',priority:'core',notes:'',sourceClassId:seed.sourceClassId||''}]}));
  const update=(id,f,v)=>setData(p=>({...p,curriculumRequirements:p.curriculumRequirements.map(r=>r.id===id?{...r,[f]:v}:r)}));
  const importClasses=()=>setData(p=>{const existing=new Set(p.curriculumRequirements.map(r=>r.sourceClassId).filter(Boolean));const addRows=p.classes.filter(c=>c.type!=='Form'&&c.subject&&Number(c.lessonsPerWeek)>0&&!existing.has(c.id)).map(c=>({id:uid(),name:c.name,year:c.year,subject:c.subject,targetType:'group',targetGroupId:c.id,lessonsPerWeek:Number(c.lessonsPerWeek),doublePeriods:0,maxSameDay:1,spread:'balanced',roomType:'No specialist room',staffingMode:c.teacherId?'fixed':'any-qualified',teacherId:c.teacherId||'',priority:c.type==='Option group'?'option':'core',notes:'',sourceClassId:c.id}));return {...p,curriculumRequirements:[...p.curriculumRequirements,...addRows]}});
  const visible=data.curriculumRequirements.filter(r=>`${r.name} ${r.year} ${r.subject}`.toLowerCase().includes(search.toLowerCase()));
  const errors=useMemo(()=>data.curriculumRequirements.flatMap(r=>{const e=[];const label=r.name||`${r.year} ${r.subject}`;if(!r.subject)e.push(`${label}: subject missing.`);if(!r.year)e.push(`${label}: year missing.`);if(Number(r.lessonsPerWeek)<=0)e.push(`${label}: lessons per week must be at least 1.`);if(r.roomType&&!['No specialist room','General classroom'].includes(r.roomType)&&!(data.rooms||[]).some(x=>x.type===r.roomType))e.push(`${label}: no ${r.roomType} exists yet.`);return e}),[data.curriculumRequirements,data.rooms]);
  return <><div className="page-title"><div><span className="eyebrow">PHASE 4</span><h1>Curriculum requirements</h1><p>Define the weekly teaching that must be fitted into the timetable.</p></div><div className="page-actions"><button className="secondary" onClick={importClasses}>Import from classes</button><button className="primary" onClick={()=>add()}>+ Add requirement</button></div></div><div className="summary-grid compact"><Metric label="Curriculum periods" value={data.curriculumRequirements.reduce((n,r)=>n+Number(r.lessonsPerWeek||0),0)} note="per week"/><Metric label="Subjects" value={new Set(data.curriculumRequirements.map(r=>r.subject).filter(Boolean)).size} note="allocated"/><Metric label="Years" value={new Set(data.curriculumRequirements.map(r=>r.year).filter(Boolean)).size} note="covered"/><Metric label="Specialist periods" value={data.curriculumRequirements.filter(r=>!['No specialist room','General classroom'].includes(r.roomType)).reduce((n,r)=>n+Number(r.lessonsPerWeek||0),0)} note="need specialist space"/></div>
  <Section eyebrow="4A · REQUIREMENTS" title="Weekly teaching requirements"><div className="table-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search curriculum…"/><div/></div>{!data.curriculumRequirements.length?<Empty title="No curriculum requirements" text="Add requirements manually or import from classes." action="Add requirement" onClick={()=>add()}/>:<div className="requirement-list">{visible.map(r=><article className="requirement-card" key={r.id}><div className="requirement-head"><input className="name-input" value={r.name||''} onChange={e=>update(r.id,'name',e.target.value)} placeholder="Label"/><button className="danger-outline small" onClick={()=>setData(p=>({...p,curriculumRequirements:p.curriculumRequirements.filter(x=>x.id!==r.id)}))}>Remove</button></div><div className="requirement-grid"><label><span>Year</span><select value={r.year} onChange={e=>update(r.id,'year',e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></label><label><span>Subject</span><input value={r.subject} onChange={e=>update(r.id,'subject',e.target.value)}/></label><label><span>Lessons/week</span><input type="number" min="1" value={r.lessonsPerWeek} onChange={e=>update(r.id,'lessonsPerWeek',e.target.value)}/></label><label><span>Double periods</span><input type="number" min="0" value={r.doublePeriods||0} onChange={e=>update(r.id,'doublePeriods',e.target.value)}/></label><label><span>Room type</span><select value={r.roomType||'No specialist room'} onChange={e=>update(r.id,'roomType',e.target.value)}>{ROOM_TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label><span>Staffing</span><select value={r.staffingMode||'any-qualified'} onChange={e=>update(r.id,'staffingMode',e.target.value)}><option value="any-qualified">Any qualified</option><option value="fixed">Fixed teacher</option></select></label>{r.staffingMode==='fixed'&&<label><span>Teacher</span><select value={r.teacherId||''} onChange={e=>update(r.id,'teacherId',e.target.value)}><option value="">Select…</option>{data.staff.map(s=><option key={s.id} value={s.id}>{s.initials||s.name}</option>)}</select></label>}</div></article>)}</div>}</Section><div className={`validation-panel ${errors.length?'warning':'success'}`}><div><span className="eyebrow">CURRICULUM CHECK</span><h2>{errors.length?`${errors.length} issue${errors.length>1?'s':''}`:'Curriculum ready'}</h2></div>{errors.length?<ul>{errors.map(e=><li key={e}>{e}</li>)}</ul>:<p>Requirements can now be cross-checked against rooms.</p>}</div></>
}

export default function AppV5(){
  const [data,setData]=useState(load); const [page,setPage]=useState('setup'); const [savedAt,setSavedAt]=useState(null);
  useEffect(()=>{const t=setTimeout(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));setSavedAt(new Date())},250);return()=>clearTimeout(t)},[data]);
  const nav=[['setup','School setup','Phase 1'],['staff','Staff','Phase 2'],['classes','Classes','Phase 3'],['curriculum','Curriculum','Phase 4'],['rooms','Rooms','Phase 5'],['constraints','Constraints','Next'],['generate','Generate timetable','Later'],['timetables','Timetables','Later'],['cover','Cover','Later']];
  const ready={setup:Boolean(data.school.name&&data.days.some(d=>d.enabled)),staff:data.staff.length>0,classes:data.classes.length>0,curriculum:data.curriculumRequirements.length>0,rooms:(data.rooms||[]).length>0};
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">TM</div><div><strong>Time Maker</strong><span>Whole-school timetabling</span></div></div><nav>{nav.map(([key,label,meta])=>{const enabled=['setup','staff','classes','curriculum','rooms'].includes(key);return <button key={key} className={`nav-item ${page===key?'active':''}`} disabled={!enabled} onClick={()=>enabled&&setPage(key)}><span>{label}</span><small>{enabled&&ready[key]?'✓ Ready':meta}</small></button>})}</nav><div className="sidebar-footer"><strong>Build progress</strong><span>Phases 1–5 enabled</span></div></aside><main className="main-content"><div className="global-bar"><div className="crumb">{data.school.name||'Unnamed school'} <span>·</span> {data.school.academicYear}</div><div className="save-state"><span className="status-dot"/>{savedAt?`Saved ${savedAt.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'Saving locally…'}</div></div>{page==='setup'&&<SchoolSetup data={data} setData={setData}/>} {page==='staff'&&<StaffManager data={data} setData={setData}/>} {page==='classes'&&<ClassesManager data={data} setData={setData}/>} {page==='curriculum'&&<CurriculumManager data={data} setData={setData}/>} {page==='rooms'&&<RoomsManager data={data} setData={setData}/>}<footer className="app-footer">Time Maker · Whole-school timetable builder · Data currently saves in this browser</footer></main></div>
}
