import React,{useState} from 'react';import {uid,activeTimetable} from './timetableCore.js';import {schoolToday,dateInfo,dateSlots,dayLessons} from './daily.js';import {suggestCover,coverCandidates} from './cover.js';import {downloadText,toCSV} from './csv.js';import {Panel,Metrics,Table} from './OperationsUI.jsx';
export default function CoverScreen({data,setData}) {
 const [date,setDate]=useState(()=>schoolToday(data)),[teacherId,setTeacherId]=useState(data.staff?.[0]?.id||''),[reason,setReason]=useState(''),[absenceSlot,setAbsenceSlot]=useState(''),[allowCombine,setAllowCombine]=useState(false),[draft,setDraft]=useState(null),[error,setError]=useState('');
 const timetable=data.publishedTimetable || activeTimetable(data),lessons=dayLessons(data,date,timetable),saved=data.coverPlans?.find(p=>p.date===date&&p.timetableId===timetable?.id),plan=draft || saved;
 function generate(){try{setDraft(suggestCover(data,date,allowCombine,timetable));setError('');}catch(e){setError(e.message);}}
 return <><div className="ops-controls"><label>Date<input type="date" value={date} onChange={e=>{if(e.target.value){setDate(e.target.value);setDraft(null);}}}/></label><span>Week {dateInfo(data,date).week}</span></div>
 <Panel title="Staff absence"><div className="ops-controls"><label>Staff<select value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Select staff</option>{(data.staff || []).map(t=><option key={t.id} value={t.id}>{t.initials} · {t.name}</option>)}</select></label><label>Periods<select value={absenceSlot} onChange={e=>setAbsenceSlot(e.target.value)}><option value="">Whole day</option>{dateSlots(data,date).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Internal note<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary" disabled={!teacherId} onClick={()=>{setData(p=>({...p,staffAbsences:[...(p.staffAbsences || []),{id:uid(),date,teacherId,reason,slotIds:absenceSlot?[absenceSlot]:[]}],coverPlans:(p.coverPlans || []).filter(x=>x.date!==date)}));setDraft(null);}}>Record absence</button></div>
 {(data.staffAbsences || []).filter(a=>a.date===date).map(a=><div className="ops-card" key={a.id}><strong>{data.staff?.find(t=>t.id===a.teacherId)?.name}</strong> · {a.slotIds?.length?'Selected period':'Whole day'} · {a.reason}<button className="text-button" onClick={()=>{setData(p=>({...p,staffAbsences:p.staffAbsences.filter(x=>x.id!==a.id),coverPlans:(p.coverPlans || []).filter(x=>x.date!==date)}));setDraft(null);}}>Remove</button></div>)}
 </Panel><Panel title="Suggested cover plan" description="Free teachers are ranked by subject expertise and remaining cover allocation. Protected periods, staff availability and daily limits are respected.">
 <div className="ops-actions"><label><span><input type="checkbox" checked={allowCombine} onChange={e=>setAllowCombine(e.target.checked)}/> Allow class-combination suggestions</span></label><button className="primary" disabled={!timetable} onClick={generate}>Generate cover suggestions</button></div>
 {error&&<p role="alert" className="ops-error">{error}</p>}
 {plan&&<><Metrics items={[["Lessons needing cover",plan.assignments.length+plan.unfilled.length,date],["Suggested cover",plan.assignments.length,'Lesson blocks'],["Unfilled",plan.unfilled.length,'Need manual arrangement'],["Combined groups",plan.assignments.filter(a=>a.combinedWithLessonId).length,'Review before accepting']]}/>
 <Table head={['Lesson','Period','Absent staff','Cover teacher','Reason']} rows={plan.assignments.map(a=>{
  const lesson=lessons.find(l=>l.id===a.lessonId),other=plan.assignments.filter(b=>b.lessonId!==a.lessonId),candidates=coverCandidates(data,date,lesson,other,allowCombine,timetable);
  return [lesson?.groupName+' · '+a.subject,lesson?.periodName,lesson?.teacherInitials,
   <select aria-label={`Cover teacher for ${lesson?.groupName} ${a.subject}`} value={a.teacherId} onChange={e=>{const c=candidates.find(x=>x.teacherId===e.target.value);if(c)setDraft({...plan,assignments:plan.assignments.map(b=>b.lessonId===a.lessonId?{...b,...c}:b)});}}>{candidates.map(c=><option key={c.teacherId} value={c.teacherId}>{c.initials || c.name}{c.specialist?' · specialist':''}</option>)}</select>,a.reason];
 })}/>
 {plan.unfilled.map(a=><p className="ops-notice" key={a.lessonId}>{a.groupName} · {a.subject}: {a.reason}</p>)}
 <div className="ops-actions"><button className="primary" disabled={!draft} onClick={()=>{setData(p=>({...p,coverPlans:[...(p.coverPlans || []).filter(x=>x.date!==date),plan]}));setDraft(null);}}>Accept cover plan</button><button className="secondary" onClick={()=>downloadText(`cover-${date}.csv`,toCSV(['date','lessonId','subject','coverTeacher','combinedWith','roomId'],plan.assignments.map(a=>[date,a.lessonId,a.subject,a.name,a.combinedWithLessonId || '',a.roomId])))}>Export cover plan</button></div><p className="hint">Accepted cover is saved against this date and timetable version. The master timetable remains unchanged.</p>
 </>}
 </Panel></>;
}
