import React,{useState,useMemo} from 'react';import {departmentDashboard} from './department.js';import {weeks,uid} from './timetableCore.js';import {Panel,Metrics,Table} from './OperationsUI.jsx';import {api} from './api.js';
export default function DepartmentScreen({data,setData,serverSession}) {
 const departments=[...new Set([...(data.departments || []),...(data.staff || []).map(t=>t.department)].filter(Boolean))];
 const [department,setDepartment]=useState(departments[0] || ''),[week,setWeek]=useState('A'),[dutyTeacher,setDutyTeacher]=useState(''),[dutyTitle,setDutyTitle]=useState(''),[location,setLocation]=useState(''),[day,setDay]=useState('mon'),[accounts,setAccounts]=useState(null),[error,setError]=useState('');
 const result=useMemo(()=>departmentDashboard(data,department,week),[data,department,week]);
 async function accountList(){try{setAccounts((await api('/api/accounts')).accounts);setError('');}catch(e){setError(e.message);}}
 return <><div className="ops-controls"><label>Department<select value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(d=><option key={d}>{d}</option>)}</select></label><label>Week<select value={week} onChange={e=>setWeek(e.target.value)}>{weeks(data).map(w=><option key={w}>{w}</option>)}</select></label></div>
 <Metrics items={[["Department staff",result.staff.length,department],["Teaching load",result.teaching,`Week ${week} periods`],["Curriculum delivered",`${result.delivered} / ${result.required}`,'Teaching periods'],["Classes without teachers",result.unstaffed.length,'Review required']]}/>
 <Panel title="Department timetable"><Table head={['Day','Period','Teacher','Subject','Class','Room']} rows={result.assignments.sort((a,b)=>a.dayKey.localeCompare(b.dayKey)||a.periodIndex-b.periodIndex).map(a=>[a.dayLabel,a.periodName,a.teacherInitials || a.teacherName,a.subject,a.groupName || a.year,a.roomCode || a.roomName])}/></Panel>
 <Panel title="Teacher allocation and load"><Table head={['Teacher','Teaching / ceiling','Contact','PPA','Leadership','Free','Cover capacity','Daily maximum']} rows={result.staff.map(t=>[t.name,`${t.allocation} / ${t.maxPeriods || 0}`,`${Math.round(t.contactRatio*100)}%`,t.ppa,t.leadership,t.free.length,t.coverCapacity,Math.max(0,...t.daily.map(d=>d.total))])}/></Panel>
 <Panel title="Room usage" description="Department usage is shown alongside whole-school usage, so shared rooms remain visible."><Table head={['Room','Type','Department periods','Whole-school periods','Available periods','Department utilisation']} rows={result.rooms.map(r=>[r.code || r.name,r.type,r.used,r.allUsed,r.available,`${Math.round(r.ratio*100)}%`])}/></Panel>
 <Panel title="Curriculum allocation"><Table head={['Year','Subject','Requirement','Required','Delivered','Missing']} rows={result.curriculum.map(r=>[r.year,r.subject,r.name,r.required,r.delivered,r.missing])}/></Panel>
 <Panel title="Classes without a valid teacher"><Table head={['Class','Year','Subject','Action']} rows={result.unstaffed.map(g=>[g.name,g.year,g.subject || 'Multiple subjects','Check curriculum staffing and regenerate'])}/></Panel>
 <Panel title="Department duties"><div className="ops-controls"><label>Teacher<select value={dutyTeacher} onChange={e=>setDutyTeacher(e.target.value)}><option value="">Select teacher</option>{result.staff.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Duty<input value={dutyTitle} onChange={e=>setDutyTitle(e.target.value)} placeholder="Lunch supervision"/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Day<select value={day} onChange={e=>setDay(e.target.value)}>{(data.days || []).filter(d=>d.enabled).map(d=><option key={d.key} value={d.key}>{d.label}</option>)}</select></label><button className="primary" disabled={!dutyTeacher||!dutyTitle.trim()} onClick={()=>{setData(p=>({...p,staff:p.staff.map(t=>t.id===dutyTeacher?{...t,duties:[...(t.duties || []),{id:uid(),title:dutyTitle.trim(),location,dayKey:day,week}]}:t)}));setDutyTitle('');}}>Assign duty</button></div><p className="hint">Publish the timetable again to include new recurring duties in the staff portal.</p>{result.staff.flatMap(t=>(t.duties || []).map(d=><div className="ops-card" key={d.id}>{t.name} · {d.title} · {d.dayKey} · Week {d.week}<button className="text-button" onClick={()=>setData(p=>({...p,staff:p.staff.map(s=>s.id===t.id?{...s,duties:s.duties.filter(x=>x.id!==d.id)}:s)}))}>Remove</button></div>))}</Panel>
 {serverSession&&<Panel title="Portal accounts"><button className="secondary" onClick={accountList}>Load accounts</button>{error&&<p role="alert" className="ops-error">{error}</p>}{accounts&&<Table head={['Username','Role','Action']} rows={accounts.map(a=>[a.username,a.role,<button className="text-button" disabled={a.id===serverSession.id} onClick={async()=>{try{await api('/api/accounts/'+a.id,{method:'DELETE'});accountList();}catch(e){setError(e.message);}}}>Remove access</button>])}/>}</Panel>}
 </>;
}
