import React,{useState,useMemo} from 'react';import {schemas,labels,autoMapping,previewImport,applyImport,exportRows,makeBackup,restoreBackup} from './exchange.js';import {parseCSV,toCSV,downloadText} from './csv.js';import {Panel,Metrics,Table} from './OperationsUI.jsx';
export default function ExchangeScreen({data,setData}) {
 const [type,setType]=useState('staff'),[text,setText]=useState(''),[sheets,setSheets]=useState([]),[sheet,setSheet]=useState(''),[rows,setRows]=useState([]),[mapping,setMapping]=useState({}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[exportType,setExportType]=useState('timetable'),[backup,setBackup]=useState(null);
 const preview=useMemo(()=>rows.length?previewImport(data,type,rows,mapping):null,[data,type,rows,mapping]);
 function chooseRows(next){setRows(next);setMapping(autoMapping(type,Object.keys(next[0] || {})));setError('');setMessage('');}
 async function fileInput(file){if(!file)return;if(file.size>10*1024*1024){setError('Upload files smaller than 10 MB.');return;}setBusy(true);try{if(file.name.toLowerCase().endsWith('.xlsx')){const {readExcel}=await import('./excel.js');const result=await readExcel(await file.arrayBuffer());setSheets(result);setSheet(result[0]?.name || '');chooseRows(result[0]?.rows || []);}else{const csv=await file.text();setText(csv);setSheets([]);chooseRows(parseCSV(csv));}}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function exportFile(format){setBusy(true);try{const result=exportRows(data,exportType);if(format==='csv')downloadText(`${exportType}.csv`,toCSV(result.headers,result.rows));else{const {writeExcel,downloadBuffer}=await import('./excel.js');downloadBuffer(`${exportType}.xlsx`,await writeExcel([{name:labels[exportType] || exportType,...result}]));}setError('');setMessage('Export created. Check your downloads.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function fullWorkbook(){setBusy(true);try{const {writeExcel,downloadBuffer}=await import('./excel.js');downloadBuffer('time-maker-school.xlsx',await writeExcel([...Object.keys(schemas),'timetable','staffAllocations'].map(key=>({name:labels[key] || key,...exportRows(data,key)}))));setError('');setMessage('School workbook created. Check your downloads for time-maker-school.xlsx.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><Panel title="Import school data" description="Import year groups and staff first, then classes and rooms, then pupils and curriculum allocations. Existing records are updated by ID; other records are retained.">
 <div className="ops-controls"><label>Import type<select value={type} onChange={e=>{setType(e.target.value);setRows([]);setSheets([]);setText('');setMessage('');}}>{Object.keys(schemas).map(key=><option key={key} value={key}>{labels[key]}</option>)}</select></label><label>CSV or Excel file<input type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>fileInput(e.target.files?.[0])}/></label><button className="secondary" onClick={()=>downloadText(`${type}-template.csv`,toCSV(schemas[type].map(f=>f.name),[]))}>Download template</button></div>
 {sheets.length>0&&<label>Excel worksheet<select value={sheet} onChange={e=>{setSheet(e.target.value);chooseRows(sheets.find(s=>s.name===e.target.value)?.rows || []);}}>{sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></label>}
 <label>Or paste CSV<textarea value={text} onChange={e=>setText(e.target.value)} placeholder={schemas[type].map(f=>f.name).join(',')}/></label><div className="ops-actions"><button className="secondary" disabled={!text||busy} onClick={()=>{try{chooseRows(parseCSV(text));}catch(e){setError(e.message);}}}>Read CSV and map columns</button></div>
 <p className="hint">Use semicolons for subject lists, pupil group IDs and available days. Identifiers are stable links between records. Blank optional fields preserve an existing value.</p>
 {rows.length>0&&<><h3>Column mapping</h3><div className="ops-grid">{schemas[type].map(f=><label key={f.name}>{f.name}{f.required?' *':''}<select value={mapping[f.name] || ''} onChange={e=>setMapping(p=>({...p,[f.name]:e.target.value}))}><option value="">Not imported</option>{Object.keys(rows[0]).map(h=><option key={h}>{h}</option>)}</select></label>)}</div></>}
 {preview&&<><Metrics items={[["New records",preview.insertCount,'Will be added'],["Updated records",preview.updateCount,'Matched by ID'],["Errors",preview.errors.length,'Must be fixed'],["Rows",rows.length,'Read from file']]}/><Table head={['Row','Error']} rows={preview.errors.map(e=>[e.row,e.message])}/><h3>Preview (first 10 records)</h3><Table head={['ID','Name / subject','Year / department']} rows={preview.valid.slice(0,10).map(r=>[r.id,r.name || r.subject,r.year || r.department || r.keyStage])}/><div className="ops-actions"><button className="primary" disabled={busy||preview.errors.length>0||!preview.valid.length} onClick={()=>{try{const latest=previewImport(data,type,rows,mapping);setData(p=>applyImport(p,type,latest));setRows([]);setMessage('Import applied. The published timetable is unchanged; regenerate and publish when ready.');setError('');}catch(e){setError(e.message);}}}>Apply validated import</button><button className="secondary" onClick={()=>downloadText('import-errors.csv',toCSV(['row','error'],preview.errors.map(e=>[e.row,e.message])))}>Export errors</button></div></>}
 {busy&&<p role="status">Processing file…</p>}{error&&<p role="alert" className="ops-error">{error}</p>}{message&&<p role="status" className="ops-success">{message}</p>}
 </Panel><Panel title="Export for your MIS" description="Export CSV or Excel files for timetable, teaching groups, rooms, staff allocations and other school records. Direct MIS connections can be added later.">
 <div className="ops-controls"><label>Export type<select value={exportType} onChange={e=>setExportType(e.target.value)}>{[...Object.keys(schemas),'timetable','staffAllocations'].map(key=><option key={key} value={key}>{labels[key] || (key==='timetable'?'Timetable':'Staff allocations')}</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>exportFile('csv')}>Export CSV</button><button className="secondary" disabled={busy} onClick={()=>exportFile('xlsx')}>Export Excel</button><button className="primary" disabled={busy} onClick={fullWorkbook}>Export school workbook</button></div><p className="hint">Timetable exports use the published copy where one exists, otherwise the selected draft. School record exports use current data.</p>
 </Panel><Panel title="Backup and restore" description="A JSON backup preserves school setup, constraints, timetable options, publications, pupils and daily changes. Portal passwords and sessions are stored separately on the server.">
 <div className="ops-controls"><button className="secondary" onClick={()=>downloadText('time-maker-backup.json',JSON.stringify(makeBackup(data),null,2),'application/json')}>Download school backup</button><label>Restore JSON backup<input type="file" accept=".json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>10*1024*1024)throw new Error('Backup exceeds 10 MB.');const restored=restoreBackup(JSON.parse(await file.text()));setBackup(restored);setError('');}catch(e){setError(e.message);}}}/></label></div>
 {backup&&<div className="ops-notice"><p>Ready to restore {backup.school.name || 'Unnamed school'}: {backup.staff.length} staff, {backup.classes.length} classes. This replaces the current school dataset.</p><button className="primary" onClick={()=>{setData(backup);setBackup(null);setRows([]);setMessage('School backup restored.');}}>Restore this backup</button><button className="text-button" onClick={()=>setBackup(null)}>Cancel</button></div>}
 </Panel><Panel title="Recent imports"><Table head={['Time','Data','Added','Updated']} rows={(data.importHistory || []).slice().reverse().map(h=>[new Date(h.at).toLocaleString(),labels[h.type],h.insertCount,h.updateCount])}/></Panel></>;
}
