import React,{useState,useMemo} from 'react';
import {modelCurriculum,applyCurriculumScenario} from './planning.js';import {uid} from './timetableCore.js';import {Panel,Metrics,Table} from './OperationsUI.jsx';
export default function PlanningScreen({data,setData}) {
 const requirements=data.curriculumRequirements || [],years=[...new Set(requirements.map(r=>r.year))],subjects=[...new Set(requirements.map(r=>r.subject))];
 const [year,setYear]=useState(years[0] || ''),[subject,setSubject]=useState(subjects[0] || ''),[lessons,setLessons]=useState(5),[name,setName]=useState(''),[message,setMessage]=useState('');
 const scenario={year,subject,lessonsPerWeek:lessons};const model=useMemo(()=>modelCurriculum(data,scenario),[data,year,subject,lessons]);
 return <><Panel title="What if the curriculum changes?" description="Model teaching periods per week before generating a timetable. Year-wide requirements are multiplied by the eligible teaching groups; group-specific requirements count once.">
 <div className="ops-controls"><label>Year<select value={year} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>Proposed lessons / group / week<input type="number" min="0" step="1" value={lessons} onChange={e=>setLessons(Math.max(0,Math.floor(Number(e.target.value))))}/></label></div>
 {!requirements.length&&<p>Add curriculum requirements in the builder first.</p>}
 <Metrics items={[["Teaching periods change",`${model.delta>=0?'+':''}${model.delta}`,`${model.groups} teaching groups`],["Current spare capacity",`${model.spare>=0?'+':''}${model.spare}`,`${subject} periods/week`],["Proposed shortfall",model.shortfall,'Teaching periods/week'],["Proposed demand",model.totalProposed,`All ${subject} requirements`]]}/>
 <p>{model.current} → {model.proposed} periods for {year} {subject}. Capacity after other subjects: {model.capacity} periods.</p>
 <p className="hint">This is a staffing model. Room availability, option clashes and the final timetable still need solving. Capacity reserves PPA and leadership time. Multi-subject staff are allocated to other curriculum demands first.</p>
 {model.otherShortfall>0&&<p className="ops-notice">Other curriculum subjects already have a {model.otherShortfall}-period staffing shortfall.</p>}
 <Table head={['Eligible teacher','Teaching capacity','Available after other curriculum']} rows={model.staff.map(r=>[r.teacher.name,r.capacity,r.remaining])}/>
 <div className="ops-controls"><label>Scenario name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Year 8 Science expansion"/></label><button className="secondary" disabled={!model.groups} onClick={()=>{setData(p=>({...p,curriculumScenarios:[...(p.curriculumScenarios || []),{...scenario,id:uid(),name:name||`${year} ${subject}: ${lessons} lessons`,savedAt:new Date().toISOString()}]}));setMessage('Scenario saved.');}}>Save scenario</button><button className="primary" disabled={!model.groups} onClick={()=>{setData(p=>applyCurriculumScenario(p,scenario));setMessage('Curriculum requirements updated. Generate a new timetable to use this allocation.');}}>Apply to curriculum</button></div>
 {message&&<p role="status" className="ops-success">{message}</p>}
 </Panel><Panel title="Saved scenarios">{(data.curriculumScenarios || []).map(s=><div className="ops-card" key={s.id}><strong>{s.name}</strong><div className="ops-actions"><button className="secondary" onClick={()=>{setYear(s.year);setSubject(s.subject);setLessons(s.lessonsPerWeek);setName(s.name);}}>Compare now</button><button className="text-button" onClick={()=>setData(p=>({...p,curriculumScenarios:p.curriculumScenarios.filter(x=>x.id!==s.id)}))}>Delete</button></div></div>)}</Panel></>;
}
