import React,{useState} from 'react';import {Panel,Metrics,Table} from './OperationsUI.jsx';
export default function PortalView({portal,onDateChange}) {
 const [tab,setTab]=useState('today');if(!portal)return <p>No portal data available.</p>;
 const {identity,today=[],master=[],classes=[],rooms=[],duties=[],free=[]}=portal;
 return <div className="portal-view"><div className="page-title"><div><span className="eyebrow">MY TIMETABLE</span><h1>{identity.name || identity.initials}</h1><p>{portal.school?.name} · Week {portal.week} · {portal.publishedAt?'Published '+new Date(portal.publishedAt).toLocaleDateString():'No timetable published yet'}</p></div><label>Date<input type="date" value={portal.date} onChange={e=>e.target.value&&onDateChange(e.target.value)}/></label></div>
 <div className="ops-actions" role="tablist" aria-label="My timetable views">{[['today','Today'],['timetable','My Timetable'],['classes','My Classes'],['rooms','My Rooms'],['cover','Cover'],['duties','Duties'],['free','Free periods']].map(([key,title])=><button role="tab" aria-selected={tab===key} className={tab===key?'primary':'secondary'} key={key} onClick={()=>setTab(key)}>{title}</button>)}</div>
 <Metrics items={[["Today's lessons",today.filter(a=>!a.cancelled).length,portal.date],["Cover",today.filter(a=>a.cover&&a.teacherId===identity.id).length,'Lessons assigned'],["Free periods",free.filter(s=>s.purpose==='Free').length,'Available today'],["Classes",classes.length,'In published timetable']]}/>
 {tab==='today'&&<Panel title="Today's lessons"><div className="ops-grid">{today.map(a=><article className={`ops-card ${a.cancelled?'cancelled':''}`} key={a.id}><h3>{a.periodName} · {a.subject}</h3><p>{a.groupName || a.year} · {a.roomCode || a.roomName}</p><p>{a.teacherName}</p><strong>{a.cancelled?'Cancelled':a.cover?'Cover'+(a.originalTeacherId===identity.id?' arranged for your lesson':' assigned'):a.absent?'Cover required':'Scheduled'}</strong>{a.originalRoomId&&a.originalRoomId!==a.roomId&&<p className="ops-notice">Room changed</p>}</article>)}</div>{!today.length&&<p>No lessons for this date.</p>}{portal.notices?.map(n=><p className="ops-notice" key={n.id}>{n.title}</p>)}</Panel>}
 {tab==='timetable'&&<Panel title="My Timetable"><Table head={['Week','Day','Period','Subject','Class','Room']} rows={master.map(a=>[a.week,a.dayLabel,a.periodName,a.subject,a.groupName || a.year,a.roomCode || a.roomName])}/></Panel>}
 {tab==='classes'&&<Panel title="My Classes"><Table head={['Class','Year','Subject','Pupils']} rows={classes.map(g=>[g.name,g.year,g.subject || 'See timetable',g.size])}/></Panel>}
 {tab==='rooms'&&<Panel title="My Rooms"><div className="ops-grid">{rooms.map(r=><article className="ops-card" key={r.id}><h3>{r.code || r.name}</h3><p>{r.building}</p></article>)}</div></Panel>}
 {tab==='cover'&&<Panel title="Cover"><Table head={['Period','Class','Subject','Room','Cover teacher']} rows={today.filter(a=>a.cover).map(a=>[a.periodName,a.groupName,a.subject,a.roomCode || a.roomName,a.teacherName])}/></Panel>}
 {tab==='duties'&&<Panel title="Duties">{duties.map((d,i)=><article className="ops-card" key={i}><strong>{d.title}</strong><p>{d.location} · {d.slotId?.split(':').at(-1)}</p></article>)}{!duties.length&&<p>No duties assigned for this date.</p>}</Panel>}
 {tab==='free'&&<Panel title="Free and protected periods"><Table head={['Period','Start','End','Purpose']} rows={free.map(s=>[s.name,s.start,s.end,s.purpose])}/></Panel>}
 </div>;
}
