import React,{useEffect,useRef,useState} from 'react';import OperationsApp from './OperationsApp.jsx';import PortalView from './PortalView.jsx';import StudentView from './StudentView.jsx';import {api,setCSRF} from './api.js';import {KEY} from './timetableCore.js';
export default function SchoolAccess() {
 const [session,setSession]=useState(undefined),[offline,setOffline]=useState(false),[error,setError]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[portal,setPortal]=useState(null),[ready,setReady]=useState(false);const revision=useRef(0),queue=useRef(Promise.resolve());
 async function establish(value){setCSRF(value.csrf);setSession(value.user);if(value.user?.role==='admin'){const school=await api('/api/school');revision.current=school.revision;if(school.data?.school)localStorage.setItem(KEY,JSON.stringify(school.data));setReady(true);}else if(value.user){setPortal(await api('/api/portal'));}}
 useEffect(()=>{let cancelled=false;api('/api/session').then(v=>{if(!cancelled)establish(v).catch(e=>setError(e.message));}).catch(()=>{if(!cancelled){setOffline(true);setSession(null);}});return()=>{cancelled=true;};},[]);
 function sync(data){const request=queue.current.catch(()=>{}).then(async()=>{const result=await api('/api/school',{method:'POST',body:{data,revision:revision.current}});revision.current=result.revision;return result;});queue.current=request;return request;}
 async function login(e){e.preventDefault();try{const value=await api('/api/login',{method:'POST',body:{username,password}});setPassword('');setError('');await establish(value);}catch(e){setError(e.message);}}
 useEffect(()=>{if(session?.role!=='admin')return;const listener=e=>sync(e.detail).catch(err=>setError(err.message));window.addEventListener('time-maker-school-saved',listener);return()=>window.removeEventListener('time-maker-school-saved',listener);},[session?.role]);
 async function logout(){try{if(session?.role==='admin')await sync(JSON.parse(localStorage.getItem(KEY) || '{}'));await api('/api/logout',{method:'POST',body:{}});setSession(null);setReady(false);setPortal(null);localStorage.removeItem(KEY);setCSRF('');}catch(e){setError(e.message);}}
 if(offline)return <OperationsApp/>;
 if(session===undefined)return <main className="ops-main"><p>Connecting to Time Maker…</p>{error&&<p role="alert">{error}</p>}</main>;
 if(!session)return <main className="ops-main login-page"><section className="panel"><span className="eyebrow">TIME MAKER</span><h1>Sign in</h1><form onSubmit={login}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="primary" type="submit">Sign in</button></form>{error&&<p role="alert" className="ops-error">{error}</p>}</section></main>;
 const PersonalView=session.role==='student'?StudentView:PortalView;
 return <><div className="portal-session"><span>{session.username}</span><button className="secondary" onClick={logout}>Sign out</button></div>{error&&<p role="alert" className="ops-error">{error}</p>}{session.role==='admin'?(ready?<OperationsApp serverSession={session} onSync={sync}/>:<p>Loading school…</p>):<main className="ops-main"><PersonalView portal={portal} onDateChange={async date=>{try{setPortal(await api('/api/portal?date='+date));setError('');}catch(e){setError(e.message);}}}/></main>}</>;
}
