import React,{useState} from 'react';import {publishTimetable,staffPortal,publishedSource} from './portal.js';import {schoolToday} from './daily.js';import {activeTimetable} from './timetableCore.js';import {Panel} from './OperationsUI.jsx';import PortalView from './PortalView.jsx';import {api} from './api.js';
export default function StaffPortalScreen({data,setData,serverSession,onSync}) {
 const [id,setId]=useState(data.publishedSchool?.staff?.[0]?.id || data.staff?.[0]?.id || ''),[date,setDate]=useState(()=>schoolToday(data)),[error,setError]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState('');
 const source=publishedSource(data);let portal=null;if(data.publishedTimetable&&source.staff?.some(t=>t.id===id))portal=staffPortal(data,id,date);
 async function publish(){try{const next=publishTimetable(data);if(onSync)await onSync(next);setData(next);setError('');setMessage('Timetable published.');}catch(e){setError(e.message);}}
 async function account(){try{await onSync(data);await api('/api/accounts',{method:'POST',body:{username,password,role:'staff',entityId:id}});setPassword('');setUsername('');setMessage('Staff account created.');setError('');}catch(e){setError(e.message);}}
 return <><Panel title="Publish and preview staff access" description="Publishing creates an approved snapshot. Draft timetable editing can continue separately."><p>Selected draft: {activeTimetable(data)?.name || 'None'}</p><div className="ops-actions"><button className="primary" onClick={publish} disabled={!activeTimetable(data)}>Publish selected timetable</button></div><label>Preview teacher<select value={id} onChange={e=>setId(e.target.value)}>{(source.staff || []).map(t=><option key={t.id} value={t.id}>{t.name || t.initials}</option>)}</select></label>
 {serverSession&&<div className="ops-controls"><label>Staff username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off"/></label><label>Initial password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength="12" autoComplete="new-password"/></label><button className="secondary" disabled={!id||!username||password.length<12} onClick={account}>Create staff account</button></div>}
 {!serverSession&&<p className="hint">This is the administrator preview. Run the included portal server to give staff their own sign-in and shared access.</p>}{error&&<p role="alert" className="ops-error">{error}</p>}{message&&<p role="status" className="ops-success">{message}</p>}</Panel>{portal&&<PortalView portal={portal} onDateChange={setDate}/>}</>;
}
