import React,{useState} from 'react';import {uid} from './timetableCore.js';import {schoolToday} from './daily.js';import {studentPortal,publishedSource} from './portal.js';import {api} from './api.js';import {Panel} from './OperationsUI.jsx';import StudentView from './StudentView.jsx';
export default function StudentPortalScreen({data,setData,serverSession,onSync}) {
 const students=data.students || [],source=publishedSource(data);const [id,setId]=useState(students[0]?.id || ''),[name,setName]=useState(''),[year,setYear]=useState(''),[studentCode,setStudentCode]=useState(''),[date,setDate]=useState(()=>schoolToday(data)),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const selected=students.find(s=>s.id===id),years=[...new Set((data.keyStages || []).flatMap(k=>k.years))];
 function add(){const code=studentCode.trim() || uid();if(students.some(s=>s.id===code)){setError('This pupil ID already exists.');return;}setData(p=>({...p,students:[...(p.students || []),{id:code,name:name.trim(),year:year||years[0]||'',groupIds:[]}]}));setId(code);setName('');setStudentCode('');setError('');}
 async function account(){try{await onSync(data);await api('/api/accounts',{method:'POST',body:{username,password,role:'student',entityId:id}});setUsername('');setPassword('');setError('');setMessage('Student account created.');}catch(e){setError(e.message);}}
 return <><Panel title="Pupil records and teaching groups" description="Assign pupils to their teaching groups. Their timetable includes only these groups and any year-wide lessons.">
 <div className="ops-controls"><label>Pupil ID<input value={studentCode} onChange={e=>setStudentCode(e.target.value)} placeholder="Optional MIS identifier"/></label><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Year<select value={year||years[0]||''} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></label><button className="primary" disabled={!name.trim()} onClick={add}>Add pupil</button></div>
 <label>Preview pupil<select value={id} onChange={e=>setId(e.target.value)}><option value="">Select pupil</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.year}</option>)}</select></label>
 {selected&&<><h3>Teaching groups for {selected.name}</h3><div className="ops-grid">{(source.classes || []).filter(g=>g.year===selected.year||g.type==='Mixed year').map(g=><label className="ops-card" key={g.id}><span><input type="checkbox" checked={(selected.groupIds || []).includes(g.id)} onChange={e=>setData(p=>({...p,students:p.students.map(s=>s.id===id?{...s,groupIds:e.target.checked?[...(s.groupIds || []),g.id]:(s.groupIds || []).filter(x=>x!==g.id)}:s)}))}/> {g.name} · {g.subject || g.type}</span></label>)}</div>
 {serverSession&&<div className="ops-controls"><label>Student username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off"/></label><label>Initial password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><button className="secondary" disabled={!username||password.length<12} onClick={account}>Create student account</button></div>}
 </>}
 {!serverSession&&<p className="hint">This is the administrator preview. Student sign-in and shared updates are available through the included portal server.</p>}{error&&<p role="alert" className="ops-error">{error}</p>}{message&&<p role="status" className="ops-success">{message}</p>}</Panel>{selected&&<StudentView key={id} portal={studentPortal(data,id,date)} onDateChange={setDate}/>}</>;
}
