import React,{useState} from 'react';import {uid,activeTimetable} from './timetableCore.js';import {schoolToday,dateInfo,dateSlots,dayLessons,dailyView,validateDailyChange} from './daily.js';import {Panel,Metrics,Table} from './OperationsUI.jsx';
export default function TodayScreen({data,setData}) {
 const [date,setDate]=useState(()=>schoolToday(data)),[type,setType]=useState('room'),[lessonId,setLessonId]=useState(''),[roomId,setRoomId]=useState(''),[groupId,setGroupId]=useState(''),[slotId,setSlotId]=useState(''),[title,setTitle]=useState(''),[error,setError]=useState('');
 const timetable=data.publishedTimetable || activeTimetable(data),lessons=dayLessons(data,date,timetable),view=dailyView(data,date,timetable),changes=(data.dailyChanges || []).filter(c=>c.date===date),absences=(data.staffAbsences || []).filter(a=>a.date===date);
 function add(){try{const change={id:uid(),date,type,title:title.trim(),lessonId:type==='room'?lessonId:'',roomId:type==='room'?roomId:'',groupId:type==='room'?'':groupId,slotId:type==='room'?'':slotId};validateDailyChange(data,change,timetable);setData(p=>({...p,dailyChanges:[...(p.dailyChanges || []),change],coverPlans:(p.coverPlans || []).filter(x=>x.date!==date)}));setTitle('');setError('');}catch(e){setError(e.message);}}
 return <><div className="ops-controls"><label>Date<input type="date" value={date} onChange={e=>{if(e.target.value){setDate(e.target.value);setLessonId('');setSlotId('');}}}/></label><button className="secondary" onClick={()=>setDate(schoolToday(data))}>Today</button><span>Week {dateInfo(data,date).week}</span><label>Week A reference Monday<input type="date" value={data.operationsSettings?.cycleAnchor || ''} onChange={e=>{if(e.target.value)setData(p=>({...p,operationsSettings:{...p.operationsSettings,cycleAnchor:e.target.value}}));}}/></label></div>
 <Metrics items={[["Staff absences",absences.length,'Recorded today'],["Cover",view.filter(a=>a.cover).length,'Lessons'],["Room changes",changes.filter(c=>c.type==='room').length,'Temporary'],["Cancelled lessons",view.filter(a=>a.cancelled).length,'Including trips/exams']]}/>
 <Panel title="Daily timetable"><Table head={['Period','Class','Subject','Teacher','Room','Status']} rows={view.sort((a,b)=>a.periodIndex-b.periodIndex).map(a=>[a.periodName,a.groupName || a.year,a.subject,a.teacherInitials || a.teacherName,a.roomCode || a.roomName,a.cancelled?'Cancelled / off timetable':a.cover?'Cover'+(a.combinedWithLessonId?' · combined groups':''):a.absent?'Absent · cover needed':a.changes.some(c=>c.type==='room')?'Room changed':'Scheduled'])}/></Panel>
 <Panel title="Absence and events"><div className="ops-grid">{absences.map(a=><article className="ops-card" key={a.id}><h3>{data.staff?.find(t=>t.id===a.teacherId)?.name} absent</h3><p>{a.slotIds?.length?'Selected period':'Whole day'}</p><p>{a.reason}</p><small>Arrange cover in the Cover screen.</small></article>)}{changes.map(c=><article className="ops-card" key={c.id}><h3>{c.title}</h3><p>{c.type} · {data.classes?.find(g=>g.id===c.groupId)?.name || (c.lessonId?'Selected lesson':'Whole school')} · {c.slotId?dateSlots(data,date).find(s=>s.id===c.slotId)?.name:'All day'}</p><button className="text-button" onClick={()=>setData(p=>({...p,dailyChanges:p.dailyChanges.filter(x=>x.id!==c.id),coverPlans:(p.coverPlans || []).filter(x=>x.date!==date)}))}>Remove change</button></article>)}</div>{!absences.length&&!changes.length&&<p>No daily changes recorded.</p>}</Panel>
 <Panel title="Add a temporary change" description="Changes apply only to this date. Trips, exams and cancellations remove the selected class periods from daily teaching; events add a notice.">
 <div className="ops-controls"><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option value="room">Room change</option><option value="trip">Trip</option><option value="exam">Exam</option><option value="cancelled">Cancelled lesson</option><option value="event">Event</option></select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Year 8 museum trip"/></label>
 {type==='room'?<><label>Lesson<select value={lessonId} onChange={e=>setLessonId(e.target.value)}><option value="">Choose lesson</option>{lessons.map(a=><option key={a.id} value={a.id}>{a.periodName} · {a.groupName} · {a.subject}</option>)}</select></label><label>New room<select value={roomId} onChange={e=>setRoomId(e.target.value)}><option value="">Choose room</option>{(data.rooms || []).map(r=><option key={r.id} value={r.id}>{r.code || r.name}</option>)}</select></label></>:<><label>Class<select value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">Whole school</option>{(data.classes || []).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Period<select value={slotId} onChange={e=>setSlotId(e.target.value)}><option value="">All day</option>{dateSlots(data,date).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></>}
 <button className="primary" disabled={!title.trim()} onClick={add}>Save daily change</button></div>{error&&<p role="alert" className="ops-error">{error}</p>}</Panel></>;
}
